### ISSUE TITLE
Can not get past Requesting encryption key

### ISSUE THREAD

**Issue by martin5256** [coolkingcole/OW_Blue_Control#1]
after trying to connect i get this 

any ideas ?  

`python3 alpha.py -s 4C:24:98:84:92:AD
Requesting encryption key...
Traceback (most recent call last):
  File "alpha.py", line 318, in <module>
    main()
  File "alpha.py", line 293, in main
    unlock_gatt_sequence(device)
  File "alpha.py", line 199, in unlock_gatt_sequence
    device.subscribe(UUIDs.UartSerialRead, callback=handle_key_response)
  File "/home/pi/.local/lib/python3.7/site-packages/pygatt/device.py", line 206, in subscribe
    self._notification_handles(uuid)
  File "/home/pi/.local/lib/python3.7/site-packages/pygatt/device.py", line 178, in _notification_handles
    value_handle = self.get_handle(uuid)
  File "/home/pi/.local/lib/python3.7/site-packages/pygatt/device.py", line 267, in get_handle
    self._characteristics = self.discover_characteristics()
  File "/home/pi/.local/lib/python3.7/site-packages/pygatt/backends/gatttool/device.py", line 17, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pygatt/backends/gatttool/device.py", line 58, in discover_characteristics
    self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 50, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 531, in discover_characteristics
    raise NotConnectedError("Characteristic discovery failed")
pygatt.exceptions.NotConnectedError: Characteristic discovery failed`

**Comment by coolkingcole** [comment]
Sorry I had made this script mostly before the pint was released. I would have to look into to this issue. It will be pretty hard to debug without having a pint. When looking at similar errors, I'd guess that the pint does have the same gatt characteristics as the ow plus so it is failing somewhere.
